In [96]:
import pandas as pd
import numpy as np

def gen_prepositions_var(prep_qtty: int, names:'list[str]' = None)-> pd.DataFrame:
    # preps = []
    if (names and (len(names) != prep_qtty)):
        raise TypeError("names length should be equal to prepositions quantity")
    posible_valuess = 2**prep_qtty

    data_dic = {}
    for x in range(prep_qtty):
        col = []
        variator = 2**(x+1)
        series_length = int(posible_valuess/variator)
        prep_value = True
        # how many series are for current prep.
        series_noumber = int(posible_valuess/series_length)
        for serie in range(series_noumber):
            # print("run:", run)
            # print("step:", [int(step) for x in range(series_length)])
            col = col + [prep_value for x in range(series_length)]
            prep_value = not prep_value

        # print("col:", col)
        name = names[x] if names else x
        data_dic[name] = col
    
    # return data_dic
    return pd.DataFrame(data_dic)


# def xor(a: bool,b: bool):
#     return (a or b) and not (a and b)

# df = gen_prepositions_var(2, ["p","q"] )
# df["p and q"] = df["p"] & df["q"]
# df["p or q"] = df["p"] | df["q"]
# df

In [95]:
df = gen_prepositions_var(3, ["p","q","r"] )
df["p and q and r"] = df["p"] & df["q"] & df["r"]
df["p or q or r"] = df["p"] | df["q"] | df["r"]

       p      q      r  p and q and r  p or q or r
0   True   True   True           True         True
1   True   True  False          False         True
2   True  False   True          False         True
3   True  False  False          False         True
4  False   True   True          False         True
5  False   True  False          False         True
6  False  False   True          False         True
7  False  False  False          False        False

In [100]:
df = gen_prepositions_var(2, ["A","B"])
df["A es subconjunto de B"] = np.logical_not(df["A"]) | df["B"]
df

       A      B  A es subconjunto de B
0   True   True                   True
1   True  False                  False
2  False   True                   True
3  False  False                   True